<?php

########################################################################
# Extension Manager/Repository config file for ext: "xliff_translationtool"
#
# Auto generated by Extension Builder 2011-09-02
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'XLIFF Translation Tool',
	'description' => 'Backendmodul to add translations for xliff',
	'category' => 'module',
	'author' => 'Thomas Layh',
	'author_email' => 'develop@layh.com',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.dev',
	'constraints' => array(
		'depends' => array(
			'cms' => '4.6.0-0.0.0',
			'extbase' => '1.4.0-0.0.0',
			'fluid' => '1.4.0-0.0.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>